version: '3.7'
services:
  copycat:
    container_name: copycat
    build:
      context: ./
      dockerfile: CopycatDockerfile
    environment:
      - DB_NAME=db0
      - DB_IP=192.168.1.188
      - DB_PORT=8089
      - MANAGER_IP=192.168.1.188
      - MANAGER_PORT=7025
      - PYTHONUNBUFFERED=1
    ports:
      - 4025:4025
